# Build and profile the C++ code
name: Check build

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"


jobs:
  check_build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt-get install qt6-base-dev qmake6 make g++ 

      - name: Run qmake
        run: qmake

      - name: Run make
        run: make --silent release

      - name: Run the program
        run: ./travis_qmake_gcc_cpp17_gprof

      - name: Produce the gprof log
        run: gprof travis_qmake_gcc_cpp17_gprof > gprof.log

      - name: Read the 100 top lines
        run: head gprof.log -n 100

