# Build and profile the C++ code
name: Check build

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"


jobs:
  check_build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      #- name: Install deps
      #  run: sudo apt-get install qmake6 qtchooser

      #- name: Use Qt6, from https://askubuntu.com/a/1460243
      #  run: qtchooser -install qt6 $(which qmake6)

      #- name: Show Qt versions
      #  run: qtchooser -list-versions

      #- name: Pick Qt6, fails according to https://askubuntu.com/a/1460243
      #  run: qtchooser -qt=qt6

      #- name: Install more deps
      #  run: sudo apt-get install qt6-base-dev

      #- name: Run qmake
      #  run: qmake6

      - name: Run qmake
        run: qmake

      - name: Run make
        run: make --silent release

      - name: Run the program
        run: ./gha_qmake_gcc_cpp17_gprof

      - name: Produce the gprof log
        run: gprof gha_qmake_gcc_cpp17_gprof > gprof.log

      - name: Read the 100 top lines
        run: head gprof.log -n 100

      - name: Get g++ version
        run: g++ --version
